Project_ReisivadTöötajad/Project_ReisivadTöötajad/Models/Spending.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ReisivadTöötajad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Spending
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spending()
        {
            this.SpendingFiles = new HashSet<SpendingFile>();
        }
    
        public int Id { get; set; }
        public int TravelId { get; set; }
        public int TypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Document { get; set; }
        public string ServiceProvider { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> VatEUR { get; set; }
        public bool PaidOut { get; set; }
    
        public virtual Travel Travel { get; set; }
        public virtual SpendingType SpendingType { get; set; }
        public virtual File File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpendingFile> SpendingFiles { get; set; }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Models/SpendingType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ReisivadTöötajad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpendingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpendingType()
        {
            this.Spendings = new HashSet<Spending>();
        }
    
        public int Id { get; set; }
        public string SpendingName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spending> Spendings { get; set; }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_ReisivadTöötajad.Models;

namespace Project_ReisivadTöötajad.Controllers
{
    public class FilesController : Controller
    {
        private TagaridaEntities db = new TagaridaEntities();

        public ActionResult Get(int? id)
        {
            if (!id.HasValue)
                return HttpNotFound();
            File file = db.Files.Find(id.Value);
            if (file == null)
                return HttpNotFound();

            return File(file.Content, file.ContentType);
        }


        // GET: Files
        public ActionResult Index()
        {
            return View(db.Files.ToList());
        }

        // GET: Files/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // GET: Files/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Content,Filename,ContentType")] File file)
        {
            if (ModelState.IsValid)
            {
                db.Files.Add(file);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(file);
        }

        // GET: Files/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,Filename,ContentType")] File file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(file).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(file);
        }

        // GET: Files/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            File file = db.Files.Find(id);
            db.Files.Remove(file);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Controllers/SpendingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_ReisivadTöötajad.Models;

namespace Project_ReisivadTöötajad.Controllers
{
    public class SpendingsController : Controller
    {
        private TagaridaEntities db = new TagaridaEntities();

        // GET: Spendings
        public ActionResult Index(int? travelid)
        {
            var spendings = db.Spendings
                .Include(s => s.File)
                .Include(s => s.Travel)
                .Include(s => s.SpendingType)
                .Where(t=> t.TravelId == travelid)
                ;

            if (travelid == null)         
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.TravelId = travelid;     
            return View(spendings.ToList());
        }


        public ActionResult RemoveFile(int? spendingid, int? fileid)  
        {
            if (spendingid == null)         
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(spendingid);      
            if (spending == null)                      
            {
                return HttpNotFound();
            }

            if (fileid == null)         
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var spendingfile = spending.SpendingFiles.Where(x => x.FileId == fileid).FirstOrDefault();        
            if (spendingfile != null)
            {
                db.SpendingFiles.Remove(spendingfile);          
                db.SaveChanges();
            }

            File deletefile = db.Files.Find(fileid);      
            db.Files.Remove(deletefile);

            return RedirectToAction("Edit", new { id = spendingid });   
        }



        // GET: Spendings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }
            return View(spending);
        }

        // GET: Spendings/Create
        public ActionResult Create(int travelid )
        {
            //if (spendingid == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            Spending spending = new Spending { TravelId = travelid };

            ViewBag.Document = new SelectList(db.Files, "Id", "Filename");
            ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName");
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName");
            return View(spending);
        }

        // POST: Spendings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TravelId,TypeId,Amount,ServiceProvider,StartDate,EndDate,VatEUR,PaidOut")] Spending spending)
        {
            if (ModelState.IsValid)
            {
                db.Spendings.Add(spending);
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = spending.Id });
            }

            ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName", spending.TravelId);
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);
            return View(spending);
        }

        // GET: Spendings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);
            return View(spending);
        }

        // POST: Spendings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "Id,TravelId,TypeId,Amount,ServiceProvider,StartDate,EndDate,VatEUR,PaidOut")] Spending spending, HttpPostedFileBase file) // lisatud , HttpPostedFileBase file
        {
            if (ModelState.IsValid)
            {
                db.Entry(spending).State = EntityState.Modified;
                db.SaveChanges();

                //lisatud
                if (file != null && file.ContentLength > 0)
                {
                    using (System.IO.BinaryReader br = new System.IO.BinaryReader(file.InputStream))
                    {                       
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        File f = new File { Content = buff, ContentType = file.ContentType, Filename = file.FileName.Split('\\').Last().Split('/').Last() };
                        db.Files.Add(f);
                        db.SaveChanges();
                        spending.Document = f.Id;
                        db.SaveChanges();

                        db.SpendingFiles.Add(new SpendingFile { SpendingId = spending.Id, FileId = f.Id });   
                        db.SaveChanges();
                    }
                } 


               return RedirectToAction("Edit");
            }
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);

            return View(spending);

        }

        // GET: Spendings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }
            return View(spending);
        }

        // POST: Spendings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Spending spending = db.Spendings.Find(id);
            db.Spendings.Remove(spending);
            db.SaveChanges();
            return RedirectToAction("Edit","Travels", new { id = spending.TravelId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Spendings/Create.cshtml
@model Project_ReisivadTöötajad.Models.Spending

@{
    ViewBag.Title = "Create";
}

<h2>Add new spending (Spendings/Create)</h2>
<div>
    @Html.ActionLink("Back to Application", "Edit", "Travels", new { id = Model.TravelId }, null)
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.TravelId, "Travel Id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TravelId, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })    @*väli on mitteaktiivne ja readonly*@
            @Html.ValidationMessageFor(model => model.TravelId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TypeId, "Type Id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Document, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Document, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.Document, "Document", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Document", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.ServiceProvider, "Service Provider", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ServiceProvider, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ServiceProvider, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, "Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, "End Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>

        @{/* TODO: Reisipäevade ja ööbimiste arvu arvutamine */}
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
  

    <div class="form-group">
        @Html.LabelFor(model => model.VatEUR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VatEUR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VatEUR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PaidOut, "Paid Out", htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.PaidOut, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PaidOut, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Spendings/Details.cshtml
@model Project_ReisivadTöötajad.Models.Spending

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Spending</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Spending Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayName("Travel Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.Id)
        </dd>

        <dt>
            @Html.DisplayName("Travel Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.TravelName)
        </dd>

        <dt>
            @Html.DisplayName("Spending Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpendingType.SpendingName)
        </dd>

        <dt>
            @Html.DisplayName("Service Provider")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceProvider)
        </dd>

        <dt>
            @Html.DisplayName("Start Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayName("End date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Travel.DailyAllowance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VatEUR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VatEUR)
        </dd>

        <dt>
            @Html.DisplayName("Paid Out")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaidOut)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.File.Filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>
    </dl>
</div>


@if (Model.Document != null)
{
    <div>
        <img src="@Url.Action("Get", "Files", new { id = Model.Document })" height="120" />
    </div>
}

@*using (Html.BeginForm("AddPicture", "People", FormMethod.Post, new { enctype = "multipart/form-data" }))*@

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Spendings/Edit.cshtml
@model Project_ReisivadTöötajad.Models.Spending

@{
    ViewBag.Title = "Edit";
}

<h2>Change spending (Spendings/Edit)</h2>
<div>
    @Html.ActionLink("Back to Application", "Edit", "Travels", new { id = Model.TravelId }, null)
</div>

@using (Html.BeginForm("Edit", "Spendings", FormMethod.Post, new { enctype = "multipart/form-data" }))  
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>Spending</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })    @*väli on mitteaktiivne ja readonly*@
        </div>
    </div>


    @*<div class="form-group">
            @Html.LabelFor(model => model.TravelId, "TravelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{/* TODO: Dropdown list eemaldada */}
                @Html.DropDownList("TravelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TravelId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.TravelId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TravelId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TravelId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TypeId, "Type Id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.ServiceProvider, "Service Provider", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ServiceProvider, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ServiceProvider, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, "Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, "End Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Travel.DailyAllowance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Travel.DailyAllowance, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Travel.DailyAllowance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VatEUR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VatEUR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VatEUR, "", new { @class = "text-danger" })
        </div>
    </div>
    @{/* TODO: raamatupidaja saab muuta seda*/}
    <div class="form-group">
        @Html.LabelFor(model => model.PaidOut, "Paid Out", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.PaidOut, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PaidOut, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
            @Html.LabelFor(model => model.Document, "Document", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Document", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <h5>Seotud failid:</h5>
    <ol>
        @foreach (var x in Model.SpendingFiles)
        {
            <li>
                <td>
                    @Html.ActionLink((x.File.Filename), "Get", "Files", new { id = x.FileId }, new { target = "_blank" })  @*FilesControlleris käivitab meetodi Get; new { target = "_blank" } avab dokumendi uues aknas*@
                    @Html.ActionLink(("Delete"), "RemoveFile", new { spendingid = Model.Id, fileid = x.FileId }, new { @class = "text-danger" })

                </td>
            </li>
        }
    </ol>

    <br />
    <h5> Lisa uus fail: </h5>
    <input type="file" name="file" id="file" />

    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}